apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapplication-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapplication
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
